[build]
  command = "next build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_ARC_EXPLORER,NEXT_PUBLIC_ARC_NETWORK_NAME,NEXT_PUBLIC_ARC_CHAIN_ID,NEXT_PUBLIC_ARC_RPC_URL,NEXT_PUBLIC_ARC_CURRENCY_SYMBOL,NEXT_PUBLIC_FACTORY_ADDRESS,NEXT_PUBLIC_USDC_ADDRESS"